# Look at the
# Discord bot settings.
bot:
  # The token of your discord bot.
  token: "<put token here -- DO NOT GIVE THIS TO ANYONE>"
  # The prefix for commands for your discord bot.
  prefix: ">>"
  # Settings for the activity or status of your bot.
  # With default settings, it will say ">>help for help!"
  # under your bot on the sidebar in your Discord server.
  activity:
    # Type can be:
    # CUSTOM
    # COMPETING
    # LISTENING
    # PLAYING
    # STREAMING
    # WATCHING
    type: PLAYING
    # The value after said setting.
    # If above is "LISTENING" and this is "your suggestions",
    # it will say "Listening to... your suggestions"
    # under your bot.
    value: "play.plasmere.net"

# For settings regarding linking of Discord channels to Minecraft.
messaging:
  # Avatar to use when sending user messages (typically when sending chat messages) to Discord.
  # ONLY APPLICABLE FOR EMBEDS!
  avatar-url: "https://minotar.net/helm/%streamline_user_uuid%/1024.png"
  # Default formats for Minecraft -> Discord and Discord -> Minecraft.
  # Per-route format is customizable in the 'routes' folder under which route you want to edit.
  default-format:
    # Minecraft -> Discord.
    from-minecraft: "%streamline_user_absolute%: %this_message%"
    # Discord -> Minecraft.
    from-discord: "&8[&9&lDiscord&8] &d%streamline_user_absolute% &9>> &r%this_message%"
  # Toggle-ables for -> Discord chat messages.
  to-discord:
    # Using Streamline Messaging Module's chat channels.
    streamline-channels: true
    # Using Streamline Groups Module's guild chat.
    streamline-guilds: true
    # Using Streamline Groups Module's party chat.
    streamline-parties: true
  # Toggle-ables for -> Minecraft chat messages.
  to-minecraft:
    # Using Streamline Messaging Module's chat channels.
    streamline-channels: true
    # Using Streamline Groups Module's guild chat.
    streamline-guilds: true
    # Using Streamline Groups Module's party chat.
    streamline-parties: true